/**
 * generated by Xtext 2.19.0
 */
package de.sos.validation;

import de.sos.validation.AbstractMORAValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class MORAValidator extends AbstractMORAValidator {
}
