/**
 * generated by Xtext 2.19.0
 */
package de.sos.web;

import de.sos.web.AbstractMORAWebModule;

/**
 * Use this class to register additional components to be used within the web application.
 */
@SuppressWarnings("all")
public class MORAWebModule extends AbstractMORAWebModule {
}
