/**
 * generated by Xtext 2.19.0
 */
package de.sos.web;

import com.google.inject.Injector;

/**
 * Initialization support for running Xtext languages in web applications.
 */
@SuppressWarnings("all")
public class MORAWebSetup /* implements MORAStandaloneSetup  */{
  @Override
  public Injector createInjector() {
    throw new Error("Unresolved compilation problems:"
      + "\nMORARuntimeModule cannot be resolved."
      + "\nMORAIdeModule cannot be resolved."
      + "\nType mismatch: cannot convert from MORAWebModule to Module");
  }
}
