/**
 * generated by Xtext 2.19.0
 */
package de.sos.mORA;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Abstract Type</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see de.sos.mORA.MORAPackage#getAbstractType()
 * @model
 * @generated
 */
public interface AbstractType extends EObject
{
} // AbstractType
