/**
 * generated by Xtext 2.19.0
 */
package de.sos.mORA;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>CSharp Options</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.sos.mORA.CSharpOptions#getBaseNamespace <em>Base Namespace</em>}</li>
 * </ul>
 *
 * @see de.sos.mORA.MORAPackage#getCSharpOptions()
 * @model
 * @generated
 */
public interface CSharpOptions extends EObject
{
  /**
   * Returns the value of the '<em><b>Base Namespace</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Base Namespace</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Base Namespace</em>' attribute.
   * @see #setBaseNamespace(String)
   * @see de.sos.mORA.MORAPackage#getCSharpOptions_BaseNamespace()
   * @model
   * @generated
   */
  String getBaseNamespace();

  /**
   * Sets the value of the '{@link de.sos.mORA.CSharpOptions#getBaseNamespace <em>Base Namespace</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Base Namespace</em>' attribute.
   * @see #getBaseNamespace()
   * @generated
   */
  void setBaseNamespace(String value);

} // CSharpOptions
