/**
 * generated by Xtext 2.19.0
 */
package de.sos.mORA;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Include</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.sos.mORA.Include#getImportUri <em>Import Uri</em>}</li>
 * </ul>
 *
 * @see de.sos.mORA.MORAPackage#getInclude()
 * @model
 * @generated
 */
public interface Include extends EObject
{
  /**
   * Returns the value of the '<em><b>Import Uri</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Import Uri</em>' attribute.
   * @see #setImportUri(String)
   * @see de.sos.mORA.MORAPackage#getInclude_ImportUri()
   * @model
   * @generated
   */
  String getImportUri();

  /**
   * Sets the value of the '{@link de.sos.mORA.Include#getImportUri <em>Import Uri</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Import Uri</em>' attribute.
   * @see #getImportUri()
   * @generated
   */
  void setImportUri(String value);

} // Include
