/**
 * generated by Xtext 2.19.0
 */
package de.sos.mORA;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Member</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.sos.mORA.Member#getDoc <em>Doc</em>}</li>
 *   <li>{@link de.sos.mORA.Member#getAnno <em>Anno</em>}</li>
 *   <li>{@link de.sos.mORA.Member#getComplexType <em>Complex Type</em>}</li>
 *   <li>{@link de.sos.mORA.Member#getPrimType <em>Prim Type</em>}</li>
 *   <li>{@link de.sos.mORA.Member#getName <em>Name</em>}</li>
 * </ul>
 *
 * @see de.sos.mORA.MORAPackage#getMember()
 * @model
 * @generated
 */
public interface Member extends EObject
{
  /**
   * Returns the value of the '<em><b>Doc</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Doc</em>' attribute.
   * @see #setDoc(String)
   * @see de.sos.mORA.MORAPackage#getMember_Doc()
   * @model
   * @generated
   */
  String getDoc();

  /**
   * Sets the value of the '{@link de.sos.mORA.Member#getDoc <em>Doc</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Doc</em>' attribute.
   * @see #getDoc()
   * @generated
   */
  void setDoc(String value);

  /**
   * Returns the value of the '<em><b>Anno</b></em>' containment reference list.
   * The list contents are of type {@link de.sos.mORA.Annotation}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Anno</em>' containment reference list.
   * @see de.sos.mORA.MORAPackage#getMember_Anno()
   * @model containment="true"
   * @generated
   */
  EList<Annotation> getAnno();

  /**
   * Returns the value of the '<em><b>Complex Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Complex Type</em>' reference.
   * @see #setComplexType(TypeDecl)
   * @see de.sos.mORA.MORAPackage#getMember_ComplexType()
   * @model
   * @generated
   */
  TypeDecl getComplexType();

  /**
   * Sets the value of the '{@link de.sos.mORA.Member#getComplexType <em>Complex Type</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Complex Type</em>' reference.
   * @see #getComplexType()
   * @generated
   */
  void setComplexType(TypeDecl value);

  /**
   * Returns the value of the '<em><b>Prim Type</b></em>' attribute.
   * The literals are from the enumeration {@link de.sos.mORA.PrimTypeLiteral}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Prim Type</em>' attribute.
   * @see de.sos.mORA.PrimTypeLiteral
   * @see #setPrimType(PrimTypeLiteral)
   * @see de.sos.mORA.MORAPackage#getMember_PrimType()
   * @model
   * @generated
   */
  PrimTypeLiteral getPrimType();

  /**
   * Sets the value of the '{@link de.sos.mORA.Member#getPrimType <em>Prim Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Prim Type</em>' attribute.
   * @see de.sos.mORA.PrimTypeLiteral
   * @see #getPrimType()
   * @generated
   */
  void setPrimType(PrimTypeLiteral value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see de.sos.mORA.MORAPackage#getMember_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link de.sos.mORA.Member#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

} // Member
