/**
 * generated by Xtext 2.19.0
 */
package de.sos.mORA;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Method</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.sos.mORA.Method#getDoc <em>Doc</em>}</li>
 *   <li>{@link de.sos.mORA.Method#getReturnProxyType <em>Return Proxy Type</em>}</li>
 *   <li>{@link de.sos.mORA.Method#getComplexType <em>Complex Type</em>}</li>
 *   <li>{@link de.sos.mORA.Method#getPrimType <em>Prim Type</em>}</li>
 *   <li>{@link de.sos.mORA.Method#getName <em>Name</em>}</li>
 *   <li>{@link de.sos.mORA.Method#getParameters <em>Parameters</em>}</li>
 *   <li>{@link de.sos.mORA.Method#getExceptions <em>Exceptions</em>}</li>
 * </ul>
 *
 * @see de.sos.mORA.MORAPackage#getMethod()
 * @model
 * @generated
 */
public interface Method extends EObject
{
  /**
   * Returns the value of the '<em><b>Doc</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Doc</em>' attribute.
   * @see #setDoc(String)
   * @see de.sos.mORA.MORAPackage#getMethod_Doc()
   * @model
   * @generated
   */
  String getDoc();

  /**
   * Sets the value of the '{@link de.sos.mORA.Method#getDoc <em>Doc</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Doc</em>' attribute.
   * @see #getDoc()
   * @generated
   */
  void setDoc(String value);

  /**
   * Returns the value of the '<em><b>Return Proxy Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Return Proxy Type</em>' reference.
   * @see #setReturnProxyType(Interface)
   * @see de.sos.mORA.MORAPackage#getMethod_ReturnProxyType()
   * @model
   * @generated
   */
  Interface getReturnProxyType();

  /**
   * Sets the value of the '{@link de.sos.mORA.Method#getReturnProxyType <em>Return Proxy Type</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Return Proxy Type</em>' reference.
   * @see #getReturnProxyType()
   * @generated
   */
  void setReturnProxyType(Interface value);

  /**
   * Returns the value of the '<em><b>Complex Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Complex Type</em>' reference.
   * @see #setComplexType(TypeDecl)
   * @see de.sos.mORA.MORAPackage#getMethod_ComplexType()
   * @model
   * @generated
   */
  TypeDecl getComplexType();

  /**
   * Sets the value of the '{@link de.sos.mORA.Method#getComplexType <em>Complex Type</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Complex Type</em>' reference.
   * @see #getComplexType()
   * @generated
   */
  void setComplexType(TypeDecl value);

  /**
   * Returns the value of the '<em><b>Prim Type</b></em>' attribute.
   * The literals are from the enumeration {@link de.sos.mORA.PrimTypeLiteral}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Prim Type</em>' attribute.
   * @see de.sos.mORA.PrimTypeLiteral
   * @see #setPrimType(PrimTypeLiteral)
   * @see de.sos.mORA.MORAPackage#getMethod_PrimType()
   * @model
   * @generated
   */
  PrimTypeLiteral getPrimType();

  /**
   * Sets the value of the '{@link de.sos.mORA.Method#getPrimType <em>Prim Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Prim Type</em>' attribute.
   * @see de.sos.mORA.PrimTypeLiteral
   * @see #getPrimType()
   * @generated
   */
  void setPrimType(PrimTypeLiteral value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see de.sos.mORA.MORAPackage#getMethod_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link de.sos.mORA.Method#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Parameters</b></em>' containment reference list.
   * The list contents are of type {@link de.sos.mORA.Parameter}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Parameters</em>' containment reference list.
   * @see de.sos.mORA.MORAPackage#getMethod_Parameters()
   * @model containment="true"
   * @generated
   */
  EList<Parameter> getParameters();

  /**
   * Returns the value of the '<em><b>Exceptions</b></em>' containment reference list.
   * The list contents are of type {@link de.sos.mORA.Exception}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Exceptions</em>' containment reference list.
   * @see de.sos.mORA.MORAPackage#getMethod_Exceptions()
   * @model containment="true"
   * @generated
   */
  EList<de.sos.mORA.Exception> getExceptions();

} // Method
