/**
 * generated by Xtext 2.19.0
 */
package de.sos.mORA;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Options</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.sos.mORA.Options#getJavaOptions <em>Java Options</em>}</li>
 *   <li>{@link de.sos.mORA.Options#getCsOptions <em>Cs Options</em>}</li>
 *   <li>{@link de.sos.mORA.Options#getCppOptions <em>Cpp Options</em>}</li>
 * </ul>
 *
 * @see de.sos.mORA.MORAPackage#getOptions()
 * @model
 * @generated
 */
public interface Options extends EObject
{
  /**
   * Returns the value of the '<em><b>Java Options</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Java Options</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Java Options</em>' containment reference.
   * @see #setJavaOptions(JavaOptions)
   * @see de.sos.mORA.MORAPackage#getOptions_JavaOptions()
   * @model containment="true"
   * @generated
   */
  JavaOptions getJavaOptions();

  /**
   * Sets the value of the '{@link de.sos.mORA.Options#getJavaOptions <em>Java Options</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Java Options</em>' containment reference.
   * @see #getJavaOptions()
   * @generated
   */
  void setJavaOptions(JavaOptions value);

  /**
   * Returns the value of the '<em><b>Cs Options</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Cs Options</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cs Options</em>' containment reference.
   * @see #setCsOptions(CSharpOptions)
   * @see de.sos.mORA.MORAPackage#getOptions_CsOptions()
   * @model containment="true"
   * @generated
   */
  CSharpOptions getCsOptions();

  /**
   * Sets the value of the '{@link de.sos.mORA.Options#getCsOptions <em>Cs Options</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Cs Options</em>' containment reference.
   * @see #getCsOptions()
   * @generated
   */
  void setCsOptions(CSharpOptions value);

  /**
   * Returns the value of the '<em><b>Cpp Options</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Cpp Options</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cpp Options</em>' containment reference.
   * @see #setCppOptions(CppOptions)
   * @see de.sos.mORA.MORAPackage#getOptions_CppOptions()
   * @model containment="true"
   * @generated
   */
  CppOptions getCppOptions();

  /**
   * Sets the value of the '{@link de.sos.mORA.Options#getCppOptions <em>Cpp Options</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Cpp Options</em>' containment reference.
   * @see #getCppOptions()
   * @generated
   */
  void setCppOptions(CppOptions value);

} // Options
