/**
 * generated by Xtext 2.19.0
 */
package de.sos.mORA;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Prim Type Decl</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.sos.mORA.PrimTypeDecl#getName <em>Name</em>}</li>
 * </ul>
 *
 * @see de.sos.mORA.MORAPackage#getPrimTypeDecl()
 * @model
 * @generated
 */
public interface PrimTypeDecl extends SingleTypeDecl
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * The literals are from the enumeration {@link de.sos.mORA.PrimTypeLiteral}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see de.sos.mORA.PrimTypeLiteral
   * @see #setName(PrimTypeLiteral)
   * @see de.sos.mORA.MORAPackage#getPrimTypeDecl_Name()
   * @model
   * @generated
   */
  PrimTypeLiteral getName();

  /**
   * Sets the value of the '{@link de.sos.mORA.PrimTypeDecl#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see de.sos.mORA.PrimTypeLiteral
   * @see #getName()
   * @generated
   */
  void setName(PrimTypeLiteral value);

} // PrimTypeDecl
