/**
 * generated by Xtext 2.19.0
 */
package de.sos.mORA;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Single Type Decl</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see de.sos.mORA.MORAPackage#getSingleTypeDecl()
 * @model
 * @generated
 */
public interface SingleTypeDecl extends TypeDecl
{
} // SingleTypeDecl
