/*
 * generated by Xtext 2.19.0
 */
package de.sos.web


/**
 * Use this class to register additional components to be used within the web application.
 */
class MORAWebModule extends AbstractMORAWebModule {
}
