/*
 * generated by Xtext 2.19.0
 */
package de.sos.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class MORAUiModule extends AbstractMORAUiModule {
}
