/**
 * generated by Xtext 2.19.0
 */
package de.sos.ui;

import de.sos.ui.AbstractMORAUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class MORAUiModule extends AbstractMORAUiModule {
  public MORAUiModule(final AbstractUIPlugin arg0) {
    super(arg0);
  }
}
