/*
 * generated by Xtext 2.19.0
 */
package de.sos.ide

import com.google.inject.Guice
import de.sos.MORARuntimeModule
import de.sos.MORAStandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class MORAIdeSetup extends MORAStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new MORARuntimeModule, new MORAIdeModule))
	}
	
}
