/**
 * generated by Xtext 2.19.0
 */
package de.sos;

import de.sos.MORAStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class MORAStandaloneSetup extends MORAStandaloneSetupGenerated {
  public static void doSetup() {
    new MORAStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
