/*
 * generated by Xtext 2.19.0
 */
package de.sos.web;

import org.eclipse.xtext.web.server.DefaultWebModule;

/**
 * Manual modifications go to {@link MORAWebModule}.
 */
@SuppressWarnings("all")
public abstract class AbstractMORAWebModule extends DefaultWebModule {

}
