/**
 * generated by Xtext 2.19.0
 */
package de.sos.ide;

import de.sos.ide.AbstractMORAIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class MORAIdeModule extends AbstractMORAIdeModule {
}
