/**
 * generated by Xtext 2.19.0
 */
package de.sos.mORA.impl;

import de.sos.mORA.Interface;
import de.sos.mORA.MORAPackage;
import de.sos.mORA.Method;
import de.sos.mORA.Parameter;
import de.sos.mORA.PrimTypeLiteral;
import de.sos.mORA.TypeDecl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Method</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link de.sos.mORA.impl.MethodImpl#getDoc <em>Doc</em>}</li>
 *   <li>{@link de.sos.mORA.impl.MethodImpl#getReturnProxyType <em>Return Proxy Type</em>}</li>
 *   <li>{@link de.sos.mORA.impl.MethodImpl#getComplexType <em>Complex Type</em>}</li>
 *   <li>{@link de.sos.mORA.impl.MethodImpl#getPrimType <em>Prim Type</em>}</li>
 *   <li>{@link de.sos.mORA.impl.MethodImpl#getName <em>Name</em>}</li>
 *   <li>{@link de.sos.mORA.impl.MethodImpl#getParameters <em>Parameters</em>}</li>
 *   <li>{@link de.sos.mORA.impl.MethodImpl#getExceptions <em>Exceptions</em>}</li>
 * </ul>
 *
 * @generated
 */
public class MethodImpl extends MinimalEObjectImpl.Container implements Method
{
  /**
   * The default value of the '{@link #getDoc() <em>Doc</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDoc()
   * @generated
   * @ordered
   */
  protected static final String DOC_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getDoc() <em>Doc</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDoc()
   * @generated
   * @ordered
   */
  protected String doc = DOC_EDEFAULT;

  /**
   * The cached value of the '{@link #getReturnProxyType() <em>Return Proxy Type</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getReturnProxyType()
   * @generated
   * @ordered
   */
  protected Interface returnProxyType;

  /**
   * The cached value of the '{@link #getComplexType() <em>Complex Type</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getComplexType()
   * @generated
   * @ordered
   */
  protected TypeDecl complexType;

  /**
   * The default value of the '{@link #getPrimType() <em>Prim Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPrimType()
   * @generated
   * @ordered
   */
  protected static final PrimTypeLiteral PRIM_TYPE_EDEFAULT = PrimTypeLiteral.BOOL;

  /**
   * The cached value of the '{@link #getPrimType() <em>Prim Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPrimType()
   * @generated
   * @ordered
   */
  protected PrimTypeLiteral primType = PRIM_TYPE_EDEFAULT;

  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getParameters() <em>Parameters</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getParameters()
   * @generated
   * @ordered
   */
  protected EList<Parameter> parameters;

  /**
   * The cached value of the '{@link #getExceptions() <em>Exceptions</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getExceptions()
   * @generated
   * @ordered
   */
  protected EList<de.sos.mORA.Exception> exceptions;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected MethodImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MORAPackage.Literals.METHOD;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getDoc()
  {
    return doc;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setDoc(String newDoc)
  {
    String oldDoc = doc;
    doc = newDoc;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MORAPackage.METHOD__DOC, oldDoc, doc));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Interface getReturnProxyType()
  {
    if (returnProxyType != null && returnProxyType.eIsProxy())
    {
      InternalEObject oldReturnProxyType = (InternalEObject)returnProxyType;
      returnProxyType = (Interface)eResolveProxy(oldReturnProxyType);
      if (returnProxyType != oldReturnProxyType)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, MORAPackage.METHOD__RETURN_PROXY_TYPE, oldReturnProxyType, returnProxyType));
      }
    }
    return returnProxyType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Interface basicGetReturnProxyType()
  {
    return returnProxyType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setReturnProxyType(Interface newReturnProxyType)
  {
    Interface oldReturnProxyType = returnProxyType;
    returnProxyType = newReturnProxyType;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MORAPackage.METHOD__RETURN_PROXY_TYPE, oldReturnProxyType, returnProxyType));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public TypeDecl getComplexType()
  {
    if (complexType != null && complexType.eIsProxy())
    {
      InternalEObject oldComplexType = (InternalEObject)complexType;
      complexType = (TypeDecl)eResolveProxy(oldComplexType);
      if (complexType != oldComplexType)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, MORAPackage.METHOD__COMPLEX_TYPE, oldComplexType, complexType));
      }
    }
    return complexType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public TypeDecl basicGetComplexType()
  {
    return complexType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setComplexType(TypeDecl newComplexType)
  {
    TypeDecl oldComplexType = complexType;
    complexType = newComplexType;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MORAPackage.METHOD__COMPLEX_TYPE, oldComplexType, complexType));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public PrimTypeLiteral getPrimType()
  {
    return primType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setPrimType(PrimTypeLiteral newPrimType)
  {
    PrimTypeLiteral oldPrimType = primType;
    primType = newPrimType == null ? PRIM_TYPE_EDEFAULT : newPrimType;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MORAPackage.METHOD__PRIM_TYPE, oldPrimType, primType));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MORAPackage.METHOD__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<Parameter> getParameters()
  {
    if (parameters == null)
    {
      parameters = new EObjectContainmentEList<Parameter>(Parameter.class, this, MORAPackage.METHOD__PARAMETERS);
    }
    return parameters;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<de.sos.mORA.Exception> getExceptions()
  {
    if (exceptions == null)
    {
      exceptions = new EObjectContainmentEList<de.sos.mORA.Exception>(de.sos.mORA.Exception.class, this, MORAPackage.METHOD__EXCEPTIONS);
    }
    return exceptions;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MORAPackage.METHOD__PARAMETERS:
        return ((InternalEList<?>)getParameters()).basicRemove(otherEnd, msgs);
      case MORAPackage.METHOD__EXCEPTIONS:
        return ((InternalEList<?>)getExceptions()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MORAPackage.METHOD__DOC:
        return getDoc();
      case MORAPackage.METHOD__RETURN_PROXY_TYPE:
        if (resolve) return getReturnProxyType();
        return basicGetReturnProxyType();
      case MORAPackage.METHOD__COMPLEX_TYPE:
        if (resolve) return getComplexType();
        return basicGetComplexType();
      case MORAPackage.METHOD__PRIM_TYPE:
        return getPrimType();
      case MORAPackage.METHOD__NAME:
        return getName();
      case MORAPackage.METHOD__PARAMETERS:
        return getParameters();
      case MORAPackage.METHOD__EXCEPTIONS:
        return getExceptions();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MORAPackage.METHOD__DOC:
        setDoc((String)newValue);
        return;
      case MORAPackage.METHOD__RETURN_PROXY_TYPE:
        setReturnProxyType((Interface)newValue);
        return;
      case MORAPackage.METHOD__COMPLEX_TYPE:
        setComplexType((TypeDecl)newValue);
        return;
      case MORAPackage.METHOD__PRIM_TYPE:
        setPrimType((PrimTypeLiteral)newValue);
        return;
      case MORAPackage.METHOD__NAME:
        setName((String)newValue);
        return;
      case MORAPackage.METHOD__PARAMETERS:
        getParameters().clear();
        getParameters().addAll((Collection<? extends Parameter>)newValue);
        return;
      case MORAPackage.METHOD__EXCEPTIONS:
        getExceptions().clear();
        getExceptions().addAll((Collection<? extends de.sos.mORA.Exception>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MORAPackage.METHOD__DOC:
        setDoc(DOC_EDEFAULT);
        return;
      case MORAPackage.METHOD__RETURN_PROXY_TYPE:
        setReturnProxyType((Interface)null);
        return;
      case MORAPackage.METHOD__COMPLEX_TYPE:
        setComplexType((TypeDecl)null);
        return;
      case MORAPackage.METHOD__PRIM_TYPE:
        setPrimType(PRIM_TYPE_EDEFAULT);
        return;
      case MORAPackage.METHOD__NAME:
        setName(NAME_EDEFAULT);
        return;
      case MORAPackage.METHOD__PARAMETERS:
        getParameters().clear();
        return;
      case MORAPackage.METHOD__EXCEPTIONS:
        getExceptions().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MORAPackage.METHOD__DOC:
        return DOC_EDEFAULT == null ? doc != null : !DOC_EDEFAULT.equals(doc);
      case MORAPackage.METHOD__RETURN_PROXY_TYPE:
        return returnProxyType != null;
      case MORAPackage.METHOD__COMPLEX_TYPE:
        return complexType != null;
      case MORAPackage.METHOD__PRIM_TYPE:
        return primType != PRIM_TYPE_EDEFAULT;
      case MORAPackage.METHOD__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case MORAPackage.METHOD__PARAMETERS:
        return parameters != null && !parameters.isEmpty();
      case MORAPackage.METHOD__EXCEPTIONS:
        return exceptions != null && !exceptions.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (doc: ");
    result.append(doc);
    result.append(", primType: ");
    result.append(primType);
    result.append(", name: ");
    result.append(name);
    result.append(')');
    return result.toString();
  }

} //MethodImpl
