/**
 * generated by Xtext 2.19.0
 */
package de.sos.mORA.impl;

import de.sos.mORA.Interface;
import de.sos.mORA.MORAPackage;
import de.sos.mORA.Parameter;
import de.sos.mORA.PrimTypeLiteral;
import de.sos.mORA.TypeDecl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Parameter</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link de.sos.mORA.impl.ParameterImpl#getComplexType <em>Complex Type</em>}</li>
 *   <li>{@link de.sos.mORA.impl.ParameterImpl#getPrimType <em>Prim Type</em>}</li>
 *   <li>{@link de.sos.mORA.impl.ParameterImpl#getProxyType <em>Proxy Type</em>}</li>
 *   <li>{@link de.sos.mORA.impl.ParameterImpl#getName <em>Name</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ParameterImpl extends MinimalEObjectImpl.Container implements Parameter
{
  /**
   * The cached value of the '{@link #getComplexType() <em>Complex Type</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getComplexType()
   * @generated
   * @ordered
   */
  protected TypeDecl complexType;

  /**
   * The default value of the '{@link #getPrimType() <em>Prim Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPrimType()
   * @generated
   * @ordered
   */
  protected static final PrimTypeLiteral PRIM_TYPE_EDEFAULT = PrimTypeLiteral.BOOL;

  /**
   * The cached value of the '{@link #getPrimType() <em>Prim Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPrimType()
   * @generated
   * @ordered
   */
  protected PrimTypeLiteral primType = PRIM_TYPE_EDEFAULT;

  /**
   * The cached value of the '{@link #getProxyType() <em>Proxy Type</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getProxyType()
   * @generated
   * @ordered
   */
  protected Interface proxyType;

  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ParameterImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MORAPackage.Literals.PARAMETER;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public TypeDecl getComplexType()
  {
    if (complexType != null && complexType.eIsProxy())
    {
      InternalEObject oldComplexType = (InternalEObject)complexType;
      complexType = (TypeDecl)eResolveProxy(oldComplexType);
      if (complexType != oldComplexType)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, MORAPackage.PARAMETER__COMPLEX_TYPE, oldComplexType, complexType));
      }
    }
    return complexType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public TypeDecl basicGetComplexType()
  {
    return complexType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setComplexType(TypeDecl newComplexType)
  {
    TypeDecl oldComplexType = complexType;
    complexType = newComplexType;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MORAPackage.PARAMETER__COMPLEX_TYPE, oldComplexType, complexType));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public PrimTypeLiteral getPrimType()
  {
    return primType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setPrimType(PrimTypeLiteral newPrimType)
  {
    PrimTypeLiteral oldPrimType = primType;
    primType = newPrimType == null ? PRIM_TYPE_EDEFAULT : newPrimType;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MORAPackage.PARAMETER__PRIM_TYPE, oldPrimType, primType));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Interface getProxyType()
  {
    if (proxyType != null && proxyType.eIsProxy())
    {
      InternalEObject oldProxyType = (InternalEObject)proxyType;
      proxyType = (Interface)eResolveProxy(oldProxyType);
      if (proxyType != oldProxyType)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, MORAPackage.PARAMETER__PROXY_TYPE, oldProxyType, proxyType));
      }
    }
    return proxyType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Interface basicGetProxyType()
  {
    return proxyType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setProxyType(Interface newProxyType)
  {
    Interface oldProxyType = proxyType;
    proxyType = newProxyType;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MORAPackage.PARAMETER__PROXY_TYPE, oldProxyType, proxyType));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MORAPackage.PARAMETER__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MORAPackage.PARAMETER__COMPLEX_TYPE:
        if (resolve) return getComplexType();
        return basicGetComplexType();
      case MORAPackage.PARAMETER__PRIM_TYPE:
        return getPrimType();
      case MORAPackage.PARAMETER__PROXY_TYPE:
        if (resolve) return getProxyType();
        return basicGetProxyType();
      case MORAPackage.PARAMETER__NAME:
        return getName();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MORAPackage.PARAMETER__COMPLEX_TYPE:
        setComplexType((TypeDecl)newValue);
        return;
      case MORAPackage.PARAMETER__PRIM_TYPE:
        setPrimType((PrimTypeLiteral)newValue);
        return;
      case MORAPackage.PARAMETER__PROXY_TYPE:
        setProxyType((Interface)newValue);
        return;
      case MORAPackage.PARAMETER__NAME:
        setName((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MORAPackage.PARAMETER__COMPLEX_TYPE:
        setComplexType((TypeDecl)null);
        return;
      case MORAPackage.PARAMETER__PRIM_TYPE:
        setPrimType(PRIM_TYPE_EDEFAULT);
        return;
      case MORAPackage.PARAMETER__PROXY_TYPE:
        setProxyType((Interface)null);
        return;
      case MORAPackage.PARAMETER__NAME:
        setName(NAME_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MORAPackage.PARAMETER__COMPLEX_TYPE:
        return complexType != null;
      case MORAPackage.PARAMETER__PRIM_TYPE:
        return primType != PRIM_TYPE_EDEFAULT;
      case MORAPackage.PARAMETER__PROXY_TYPE:
        return proxyType != null;
      case MORAPackage.PARAMETER__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (primType: ");
    result.append(primType);
    result.append(", name: ");
    result.append(name);
    result.append(')');
    return result.toString();
  }

} //ParameterImpl
