/**
 * generated by Xtext 2.19.0
 */
package de.sos.mORA.impl;

import de.sos.mORA.MORAPackage;
import de.sos.mORA.SingleTypeDecl;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Single Type Decl</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class SingleTypeDeclImpl extends TypeDeclImpl implements SingleTypeDecl
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SingleTypeDeclImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MORAPackage.Literals.SINGLE_TYPE_DECL;
  }

} //SingleTypeDeclImpl
