/*
 * generated by Xtext 2.19.0
 */
package de.sos


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class MORAStandaloneSetup extends MORAStandaloneSetupGenerated {

	def static void doSetup() {
		new MORAStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
